services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: translation_batch_app
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - STREAMLIT_SERVER_FILE_WATCHER_TYPE=auto
    restart: unless-stopped
